/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface ProjectSubmission {
  'transactionHash' : string,
  'paymentStatus' : string,
  'numberOfPages' : string,
  'additionalNotes' : string,
  'clientName' : string,
  'projectDescription' : string,
  'package' : string,
  'needsBranding' : boolean,
  'whatTheyNeed' : string,
  'needsBooking' : boolean,
  'businessName' : string,
  'businessType' : string,
  'needsPaymentIntegration' : boolean,
  'email' : string,
  'currentWebsite' : string,
  'needsDashboard' : boolean,
  'needsContentWriting' : boolean,
  'projectId' : string,
  'timestamp' : bigint,
  'needsContactForm' : boolean,
  'contentReadiness' : string,
  'inspirationLinks' : string,
  'timeline' : string,
}
export interface _SERVICE {
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getProjects' : ActorMethod<[], Array<ProjectSubmission>>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'submitProject' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      string,
      string,
      string,
      string,
    ],
    string
  >,
  'updatePaymentStatus' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];