/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ProjectSubmission = IDL.Record({
  'transactionHash' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'numberOfPages' : IDL.Text,
  'additionalNotes' : IDL.Text,
  'clientName' : IDL.Text,
  'projectDescription' : IDL.Text,
  'package' : IDL.Text,
  'needsBranding' : IDL.Bool,
  'whatTheyNeed' : IDL.Text,
  'needsBooking' : IDL.Bool,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'needsPaymentIntegration' : IDL.Bool,
  'email' : IDL.Text,
  'currentWebsite' : IDL.Text,
  'needsDashboard' : IDL.Bool,
  'needsContentWriting' : IDL.Bool,
  'projectId' : IDL.Text,
  'timestamp' : IDL.Int,
  'needsContactForm' : IDL.Bool,
  'contentReadiness' : IDL.Text,
  'inspirationLinks' : IDL.Text,
  'timeline' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(ProjectSubmission)], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ProjectSubmission = IDL.Record({
    'transactionHash' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'numberOfPages' : IDL.Text,
    'additionalNotes' : IDL.Text,
    'clientName' : IDL.Text,
    'projectDescription' : IDL.Text,
    'package' : IDL.Text,
    'needsBranding' : IDL.Bool,
    'whatTheyNeed' : IDL.Text,
    'needsBooking' : IDL.Bool,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'needsPaymentIntegration' : IDL.Bool,
    'email' : IDL.Text,
    'currentWebsite' : IDL.Text,
    'needsDashboard' : IDL.Bool,
    'needsContentWriting' : IDL.Bool,
    'projectId' : IDL.Text,
    'timestamp' : IDL.Int,
    'needsContactForm' : IDL.Bool,
    'contentReadiness' : IDL.Text,
    'inspirationLinks' : IDL.Text,
    'timeline' : IDL.Text,
  });
  
  return IDL.Service({
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(ProjectSubmission)], ['query']),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };